### ISSUE TITLE
systelab-two-list: more than one with the same name. Wrong management

### ISSUE THREAD

**Issue by rrubio2** [systelab/systelab-components#113]
**To Reproduce**
1. Create a two-list control with two items with the same name 
2. Select one of them and click on '>' button

**Expected behavior**
Only the selected one has to be moved

**Expected behavior**
Only the selected one has to be moved

**Actual behavior**
Both of them are deleted from source box. Only one of them appears in destination box

**Comment by alfonsserra** [comment]
Solved in PR #125
