### ISSUE TITLE
systelab-two-list: Disable drag&drop 

### ISSUE THREAD

**Issue by joaquimvila** [systelab/systelab-components#134]
**Description**
In systelab-two-list component, it is not possible to disable the drag&drop feature. In some environments (i.e when using touch screen with gloves), drag&drop metaphors are not suitable and it is better to do not allow it.

**Desired solution**
A new boolean input to configure the if the drag&drop is enabled or not. By default, the drag&drop should be enabled.

**Comment by joaquimvila** [comment]
Resolved for angular 5 in PR #135

**Comment by joaquimvila** [comment]
Resolved for angular 7 in PR #137

**Comment by joaquimvila** [comment]
Compatibility problems found when integrating version 5.4.32 of systelab-components into the Snow project. Resolved by adding the possibility of adding later versions of a related dependency (angular-split).

**Comment by alfonsserra** [comment]
See PR #135 and #137
