### ISSUE TITLE
Sass: Replace the size attribute of bootstrap by width & size

### ISSUE THREAD

**Issue by rochiebcn** [systelab/systelab-components#172]
In the bootstrap 4.3.0 has been marked as deprecated the size() method and will be removed entirely in v5. 

We have a lot of references to this function in our sass files. To prevent future problems, it's necessary to replace by the attributes width and height as is described in the issue of bootstrap [github](https://github.com/twbs/bootstrap/pull/28067)

The solution is to replace the ` @include size($icon-header-size);` by  
`width: $icon-header-size;
    height: $icon-header-size;`

**Comment by vinyulis** [comment]
We already have our own size() in systelab-components/src/app/systelab-components/sass/_mixins.scss
I don't know why but bootstrap size() is used instead our own size() declared in mixins. Maybe we should investigate this before doing any change in all the scss files.
