### ISSUE TITLE
add/change css for disabled combobox

### ISSUE THREAD

**Issue by pepgrifell** [systelab/systelab-components#218]
When a combobox (that extends from AbstractCombobox) is disabled, it is painted in white and the combobox and the value selected is almost not visible. 

This is how the combobox is seen:
![image](https://user-images.githubusercontent.com/6485894/57524732-00748380-7329-11e9-9567-178409c621c6.png)

It should be nice to have the same gray color as the input form fields:
![image](https://user-images.githubusercontent.com/6485894/57524876-6cef8280-7329-11e9-81f7-cde2f6083c14.png)

**Comment by carlosra85** [comment]
Already reported in #178

**Comment by pepgrifell** [comment]
ups, sorry for that !
