### ISSUE TITLE
Content Menu with child error after close and reopen

### ISSUE THREAD

**Issue by carlosra85** [systelab/systelab-components#385]
**Describe the bug**
Content Menu with child error after close and reopen. In grids context menu it seems to work correctly, but in the context menu component no.

**To Reproduce**
1. In Showcase go to Utils - Context Menu - Context Menu with children
2. Click on Context Menu with Children and navigate through child options
3. Close the Context Menu by clicking anywhere in screen
4. Click again on Context Menu with Children and see now navigation is not stable

**Screenshots**
First time:
![image](https://user-images.githubusercontent.com/27365557/86465339-b66f0e00-bd31-11ea-9ed1-a43fdc04041d.png)

Second time:
![image](https://user-images.githubusercontent.com/27365557/86465361-bff87600-bd31-11ea-8a0e-cdc3c5e63ae8.png)

**Comment by oGalceran1** [comment]
If you need help or comment this issue, don't hesitate to contact me
