### ISSUE TITLE
listbox: Infinite loop in listbox when using parameter selectFirstItem = true

### ISSUE THREAD

**Issue by carlosra85** [systelab/systelab-components#402]
Infinite loop in listbox when using parameter selectFirstItem = true. The component works fine but it results in a log error:

![image](https://user-images.githubusercontent.com/27365557/95856297-19713780-0d5a-11eb-926e-87a46db8178b.png)

**Comment by olgapuig** [comment]
This issue was tested in the last release of Modulab and can be closed.
