### ISSUE TITLE
Karma update (current is v6.3.8)

### ISSUE THREAD

**Issue by olgapuig** [systelab/systelab-components#414]
The current Karma version is 4.3.0. 'npm audix fix' recommends to update Karma to the latest v6.3.8

After upgrading it, some tests fails due to " Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)". This is because the test execution requires more memory and it can be assigned for the "npm run test" with --max_old_space_size=8192

**Comment by carlosra85** [comment]
Already in 6.4.2
