### ISSUE TITLE
GridHeaderContextMenuComponent raises a "Method not implemented" error when a refresh is performed

### ISSUE THREAD

**Issue by RubKrmon** [systelab/systelab-components#419]
**Describe the bug**
A "Method not implemented" error is raised when a call to the refresh function is being executed in the component.

**To Reproduce**
1. Perform an action that raises a component refresh.

**Expected behavior**
Have this method implemented by default. If it is needed a diferent behavior extend the class and implement it.

**Screenshots**
![image](https://user-images.githubusercontent.com/34563574/108348225-ca448300-71e1-11eb-974c-2e4390f25bcb.png)

**Comment by olgapuig** [comment]
Reopen due to the verification is required.
