### ISSUE TITLE
Context Help tours

### ISSUE THREAD

**Issue by apenalver2** [systelab/systelab-components#424]
AccuTrak 2.0 has implemented the help contextual tours, would be interesting to include this functionality in the systelab-components.

The tour is describing the functionality of the selected components around the page.

![image](https://user-images.githubusercontent.com/34027110/110299930-96959580-7ff6-11eb-8bae-f84f4a503d32.png)

**Comment by carlosra85** [comment]
Not a common necessity for the moment. Not planned
