### ISSUE TITLE
Create a new datepicker (JS library) instead of PrimeNG usage

### ISSUE THREAD

**Issue by olgapuig** [systelab/systelab-components#434]
**Is your feature request related to a problem? Please describe.**
Create a new datepicker (JS library) instead of PrimeNG usage

**Describe the solution you'd like**
All the current datepicker features must be available in the new JS library
This component must have identifiers to be able to create the accessors in the library systelab-components-test

**Comment by olgapuig** [comment]
The priority is to find out a Javascript based.

**Comment by olgapuig** [comment]
Backlog grooming. Improve the UX of the systelab-date-time component.

**Comment by amgart** [comment]
From GEMweb Plus we need the date picker able to use different date time formats, not depending on the selected language (as the current Systelab components), as in GEMweb Plus the user can change in a setup screen the date time format used in the whole application.

Moreover, we would like that the new component use the standard ISO8601 for date time formats, as the current Systelab Components doesn't.

**Comment by olgapuig** [comment]
After further analysis, this ticket is rejected because the current component covers the project needs. 
A new issue will be created to extend the current component to allow the use of different date formats independently of the locale.
