### ISSUE TITLE
Identify and share common helpers

### ISSUE THREAD

**Issue by oGalceran1** [systelab/systelab-components#437]
**Is your feature request related to a problem? Please describe.**
All the applications work with numbers and dates. There are a set of helpers that manage these types of information. It could be interesting to share them in the systelab-components

**Describe the solution you'd like**
Evaluate if all the projects have a datehelper and a numberhelper and share their content. Try to get a common consense and share them in the library. Evaluate also other possible helpers like stringHelper, etc...

**Describe alternatives you've considered**
We can generate a helpers library (systelab-helpers) instead of being part of the systelab-components.

**Additional context**
May be there are other helpers more critical related with business that can be part of another more private library (for example: formula-helper)

**Comment by olgapuig** [comment]
@oGalceran1 could you share the source code of the proposed helpers? I think it would help us assessing the best way to include it in the shared libraries.

**Comment by oGalceran1** [comment]
[HelpersCode.zip](https://github.com/systelab/systelab-components/files/6181230/HelpersCode.zip)

Here there are the helpers used in Anthema and that has sense to share with others
