### ISSUE TITLE
Include the numpadDecimalNumericDirective

### ISSUE THREAD

**Issue by oGalceran1** [systelab/systelab-components#442]
**Is your feature request related to a problem? Please describe.**
In some places, the numpad decimal separator should be locale reactive, in the sense that in Spanish, the "." should be changed by the ","

**Describe the solution you'd like**
A Directive has been created to put the decimal separator according to the locale when pressed the "." in the numpad keyboard.

**Describe alternatives you've considered**
The directive can be included in the Systelab-components

**Additional context**

**Comment by olgapuig** [comment]
This change is required for Angular10.

**Comment by olgapuig** [comment]
Consider to extend the pipe NumberFormatPipe from the systelab-translate, so it can be used by any components.
For example, we need this behavior in the DecimalInputCellEditorComponent inside an ag-grid.
