### ISSUE TITLE
Rename async to waitForAsync - deprecated, to be removed in angular v13

### ISSUE THREAD

**Issue by atzurk** [systelab/systelab-components#460]
**Is your feature request related to a problem? Please describe.**
async operator is deprecated, and it's going to be removed in angular v12-13

**Describe the solution you'd like**
refactor lines that use async to be replaced with waitForAsync

**Describe alternatives you've considered**
None

**Additional context**

https://angular.io/guide/updating-to-version-11

![image](https://user-images.githubusercontent.com/39374121/117950822-dee17480-b313-11eb-9a04-0670fe026092.png)

**Comment by alfonsserra** [comment]
See PR #468
