### ISSUE TITLE
Add range option to slider

### ISSUE THREAD

**Issue by OscarDeDios** [systelab/systelab-components#497]
**Is your feature request related to a problem? Please describe.**
In some forms we need to inform a minimum and maximum value, for this the slider with range option is the best option.

**Describe the solution you'd like**
Add a  new propery "range" object with min and max properties.
The slider is made with the native HTML5 input range. It doesn't have the range option, but it could be simulated using two inputs range in the same position and controlling the range behavior with javascript.

**Comment by FredKF** [comment]
Hello @OscarDeDios , as the slider with range option is going to be used in some forms, I think it would be better if we create a brand new component implementing this feature, something like in this screenshot:

![range slider](https://user-images.githubusercontent.com/25246376/143412724-96c20675-6557-4414-9f03-134b03d7287a.png)

I'll stay tuned 

Thanks !
