### ISSUE TITLE
Error selected multiple combo in listbox and combobox

### ISSUE THREAD

**Issue by Stela303** [systelab/systelab-components#543]
### **Description**
Selected items do not appear by default in listbox and combobox component.

### **Actual behaviour**
Steps to reproduce the behaviour in **listobox**:
1. Select multiple items from the list.
2. Click on Submit button.
3. Go back.
4. Open the listbox.
5. The list does not show the selected items.

![image](https://user-images.githubusercontent.com/48439749/150505591-e3e2ee0d-67aa-457b-9104-460df70ee6fe.png)

Steps to reproduce the behaviour in **combobox**:
1. Select multiple items from the combobox.
2. Close combobox.
3. Open combobox.
4. The list does not show the selected items.

![image](https://user-images.githubusercontent.com/48439749/150744786-2ed2ca2c-143d-41d7-819a-02add957bcc9.png)

### **Expected behaviour**
**Listbox**:
![image](https://user-images.githubusercontent.com/48439749/150505655-3b8bfb4b-acf9-478d-b7a2-7d6ae2a0fe33.png)

**Combobox**:
![image](https://user-images.githubusercontent.com/48439749/150744849-d467b670-6b2d-4177-96e9-5cae0f9795fa.png)

**Comment by carlosra85** [comment]
It keeps failing in tree listbox.
It seems the cause of the error is ag-grid version forcing type of row node id to string and systelab-components work with number ids many times
