### ISSUE TITLE
Close all dialogs is not done in dialog-ref.ts file

### ISSUE THREAD

**Issue by Saul98** [systelab/systelab-components#547]
**Describe the bug**
"Close all dialogs" procedure in dialog-ref is not developed yet and it's necessary in the product.

It can be fixed if you use the OverlayKeyboardDispatcher or the OverlayOutsideClickDispatcher, both have a method that shows all open overlays, by scrolling through them you can close them all.

**Comment by olgapuig** [comment]
This is not needed.
