### ISSUE TITLE
Improve autocomplete UX

### ISSUE THREAD

**Issue by OscarDeDios** [systelab/systelab-components#609]
**Is your feature request related to a problem? Please describe.**
When an autocomplete combo box has data and the user opens the dropdown to choose another option the dropdown is empty because only shows the options that have the input text. To see what options are available the user has to delete the input text. This is very slow and annoying.

**Describe the solution you'd like**
It's ok that when a user writes content in the autocomplete the dropdown only shows the content that contains input search, but if the user clicks in the dropdown arrow it would be useful to show all the options to be able to choose one by clicking.

**Comment by olgapuig** [comment]
Consider to use the combo with search 
Use the option "with restore" that adds an X
Review how this component is implemented in the community.

**Comment by carlosra85** [comment]
Duplicated #785
