### ISSUE TITLE
In the datepicker component, when using Italian or Chinese language, the days on the right side are not shown inside the calendar dialog

### ISSUE THREAD

**Issue by JordiCela** [systelab/systelab-components#643]
**Describe the bug**
In the datepicker component, when using Italian or Chinese language, the days on the right side are not shown inside the calendar dialog

**To Reproduce**
1. Login to the application using Italian or Chinese language
2. Go to a 'Date' field
3. Click on the field to open the Calendar
4. Focus on the days of the week

**Expected behavior**
All the days of the week are shown inside the calendar dialog.

**Current behavior**
The days on the right side are not shown inside the calendar dialog.

![Defect](https://user-images.githubusercontent.com/41988810/191520630-f63752ef-c270-4837-ace3-709c016663cf.jpg)

![Defect 2jpg](https://user-images.githubusercontent.com/41988810/191525277-a41da43d-e91c-4870-a312-d4cfa2257806.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 105.0.5195.127

**Comment by diegocj28** [comment]
This issue cannot be implemented because the required changes to the PrimeNG Calendar component should be made, and this is out of our scope. A better solution would be to build our calendar to avoid this dependency, but the cost would be too high to solve a problem that has a workaround.
