### ISSUE TITLE
Add a dismiss option on toasts

### ISSUE THREAD

**Issue by joaquimvila** [systelab/systelab-components#686]
**Is your feature request related to a problem? Please describe.**
According to [systelab guidelines](https://systelab.github.io/systelab-components-guidelines/content.html?components/toast), toast components may have a "dismiss" option that allow to close them before they fade out automatically after a certain time. However, current "systelab-toast" component does not allow this option.

**Describe the solution you'd like**
New configuration option in toast component to allow showing a dismiss button (i.e as in guideline, circular with a cross icon on it).
In order to do not affect existing usages, this new option should be disabled by default.

**Comment by fjaguado** [comment]
In order to unify changes for the same component, in this issue we will add an options for configuring the width of the toast component. See #744 for more details
