### ISSUE TITLE
The dropdown cell width is incorrect, and the content is not displayed properly.

### ISSUE THREAD

**Issue by joan6149** [systelab/systelab-components#910]
**Describe the bug**

When we click on a tree-type combobox, the second time we expand the combobox, it does not display correctly, significantly narrowing the width of each cell and preventing the text inside from being visible.

This has been detected in v. 17.1.10

**To Reproduce**
1. Go to any Tree type Combobox
2. Click to show the list of elements
3. Click another time to collapse elements
4. Click now to expand elements again.
5. The elements are not displayed correctly.

**Expected behavior**
The elements should be displayed when the user clicks on the dropdown

**Screenshots**
![image](https://github.com/user-attachments/assets/863c9d33-9d02-480d-97a1-9f018d627ee6)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, edge
 - Chrome version 127
 - Edge version 128

**Comment by jferrer1W** [comment]
created from another account
