### ISSUE TITLE
Allow datepicker to have a default blank value

### ISSUE THREAD

**Issue by Franek75** [systelab/systelab-components#937]
**Is your feature request related to a problem? Please describe.**
In our project, in some cases it would be convenient that datepicker's default value was blank.
E.g. for datepickers in filter areas we do not want a default value to be mandatory. We want the initial value being able to be blank, and the user selecting a date if he/she wants to (considering also that it is not a mandatory field)

**Describe the solution you'd like**
A parameter telling whether the default blank is allowed or not would be great.

**Describe alternatives you've considered**
None considered.

**Additional context**
E.g. we would be interested in the following "Date of Birth" datepicker field to appear blank, instead of being initially set to the current date:
![FilterDateOfBirth](https://github.com/user-attachments/assets/ad537aa4-600d-4627-bf4a-dc39da2633e5)

**Comment by carlosra85** [comment]
I think this is already possible it depends on the variable you are binding to [(currentDate)], is you set a variable with an empty initial value it should work

**Comment by Franek75** [comment]
Solution given by @carlosra85 worked!
So this change is not necessary.
